default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      # - id: go-vet-mod
      - id: go-fmt
      - id: go-imports
        args: [-w]
      - id: golangci-lint-mod
        args: [--fix]
      - id: go-test-mod
      - id: go-build-mod
      - id: go-mod-tidy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        # args: [] pass allowed types as blank separated list here
