# https://taskfile.dev

version: '3'

vars: {}

tasks:
  setup:
    desc: Install dependencies
    run: once
    deps: [brew]
    cmds:
      - pre-commit install

  brew:
    desc: Install dependencies with brew
    internal: true
    platforms: [darwin]
    cmd: brew bundle
    status:
      - brew bundle check --verbose

  lint:
    desc: Run linters
    aliases: [l]
    cmds:
      - go mod tidy
      - golangci-lint run --fix ./...

  test:
    desc: Run go tests
    aliases: [t]
    cmd: gotestsum

  test-watch:
    desc: Run go tests with coverage and watch
    aliases: [tw]
    cmd: gotestsum --watch -- -coverprofile=coverage.out ./...

  test-coverage:
    desc: Run go tests and display coverage
    aliases: [tc]
    cmds:
      - gotestsum -- -coverprofile=coverage.out ./...
      - go tool cover -func coverage.out
      - go tool cover -html coverage.out

  test-bench:
    desc: Run go benchmarks
    aliases: [tb]
    cmd: go test -run=NO_TEST -bench=. -benchmem -benchtime=1s ./...
